#!/bin/bash
# tts-kokoro-install.sh — Set up the dedicated Kokoro TTS server install
# under ~/.claude/services/kokoro/. Requires server.py + requirements.txt to be
# present in the install dir first (copy them from tts/kokoro-server/).
# Idempotent: safe to re-run to upgrade pip deps or rebuild the venv.
# Override the target dir with KOKORO_INSTALL_DIR (used for testing).
set -e

INSTALL_DIR="${KOKORO_INSTALL_DIR:-$HOME/.claude/services/kokoro}"
PLIST_LABEL="com.claude.tts-kokoro"
PLIST_PATH="$HOME/Library/LaunchAgents/$PLIST_LABEL.plist"
SERVER_PORT=8321

# --- Pre-flight: server files must already be staged in INSTALL_DIR ---
if [ ! -f "$INSTALL_DIR/server.py" ] || [ ! -f "$INSTALL_DIR/requirements.txt" ]; then
  echo "ERROR: Kokoro server files not found in $INSTALL_DIR" >&2
  echo "       Copy them there first:" >&2
  echo "         mkdir -p \"$INSTALL_DIR\"" >&2
  echo "         cp tts/kokoro-server/server.py tts/kokoro-server/requirements.txt \"$INSTALL_DIR\"/" >&2
  exit 1
fi

# Kokoro 0.9.2 requires Python >=3.10 and <3.13. Prefer python3.12, then
# python3.11, then python3.10, then fall back to plain python3 if it fits.
PY=""
for candidate in python3.12 python3.11 python3.10 python3; do
  CAND_PATH=$(command -v "$candidate" 2>/dev/null || true)
  [ -z "$CAND_PATH" ] && continue
  V=$("$CAND_PATH" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")' 2>/dev/null || echo "")
  MAJOR=${V%.*}
  MINOR=${V#*.}
  if [ "$MAJOR" = "3" ] && [ "$MINOR" -ge 10 ] && [ "$MINOR" -lt 13 ]; then
    PY="$CAND_PATH"
    PY_VER="$V"
    break
  fi
done
if [ -z "$PY" ]; then
  echo "ERROR: no compatible python found (need >=3.10, <3.13 for kokoro 0.9.2)." >&2
  echo "       Install with: brew install python@3.12" >&2
  exit 1
fi
echo "Using $PY (Python $PY_VER)"

# --- Virtualenv ---
if [ ! -d "$INSTALL_DIR/venv" ]; then
  echo "Creating virtualenv at $INSTALL_DIR/venv ..."
  "$PY" -m venv "$INSTALL_DIR/venv"
fi
echo "Upgrading pip and installing requirements (this is slow on first run) ..."
"$INSTALL_DIR/venv/bin/pip" install --upgrade pip
"$INSTALL_DIR/venv/bin/pip" install -r "$INSTALL_DIR/requirements.txt"

# --- Entrypoint ---
cat > "$INSTALL_DIR/start.sh" <<EOF
#!/bin/bash
# Auto-generated by tts-kokoro-install.sh — do not edit.
cd "\$(dirname "\$0")"
exec ./venv/bin/uvicorn server:app --host 127.0.0.1 --port $SERVER_PORT
EOF
chmod +x "$INSTALL_DIR/start.sh"

# --- Launchd ---
if [ "${1:-}" = "--with-launchd" ]; then
  mkdir -p "$HOME/Library/LaunchAgents"
  cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$PLIST_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$INSTALL_DIR/start.sh</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$INSTALL_DIR/kokoro.log</string>
  <key>StandardErrorPath</key>
  <string>$INSTALL_DIR/kokoro.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
  </dict>
</dict>
</plist>
EOF
  echo "Wrote launchd plist to $PLIST_PATH"

  # Idempotent (re)load
  launchctl bootout "gui/$UID/$PLIST_LABEL" 2>/dev/null || true
  launchctl bootstrap "gui/$UID" "$PLIST_PATH"
  echo "launchd agent bootstrapped — polling /voices for readiness ..."

  for i in $(seq 1 30); do
    if curl -fsS --max-time 2 "http://127.0.0.1:$SERVER_PORT/voices" >/dev/null 2>&1; then
      n=$(curl -fsS --max-time 2 "http://127.0.0.1:$SERVER_PORT/voices" | jq -r '.voices | length')
      echo "Kokoro server is up. Voices available: $n"
      exit 0
    fi
    sleep 2
  done
  echo "WARN: server did not respond within 60s. Check $INSTALL_DIR/kokoro.log" >&2
  exit 1
fi

echo ""
echo "Install staged at $INSTALL_DIR"
echo "Run start.sh manually to smoke-test, then re-run this script with"
echo "--with-launchd to install the launchd agent."
